# Train BSM Test BSM
# No vega state
# 60-30

train_env:
  class_name: DREnv
  params:
    portfolio:
      ref: bsm_portfolio
    episode_length: 30
    vega_ratio: True
    scale_action: True
    action_low: -0.2
    action_high: 1.2
    states:
      - stock_price
      - hedging_implvol
      - port_delta
      - port_gamma
      - ttm
      - inst_vol

eval_env:
  class_name: DREnv
  params:
    portfolio:
      ref: sabr_portfolio
    episode_length: 30
    vega_ratio: True
    scale_action: True
    action_low: -0.2
    action_high: 1.2
    states:
      - stock_price
      - hedging_implvol
      - port_delta
      - port_gamma
      - ttm
      - inst_vol

bsm_portfolio:
  class_name: Portfolio
  params:
    sde:
      ref: bsm_sde
    client_trade_poisson_rate: 1.0
    client_options:
      class_name: VanillaOption
      params:
        sde:
          ref: bsm_sde
        call: [True]
        moneyness: [1.0]
        ttm: [60]
        shares: [-1.0]
        sim_moneyness_mean: 1.0
        sim_moneyness_std: 0.0
        sim_ttms: [60]
        sim_call: [True]
    hedging_options:
      class_name: VanillaOption
      params:
        sde:
          ref: bsm_sde
        sim_moneyness_mean: 1.0
        sim_moneyness_std: 0.0
        sim_ttms: [30]
        sim_call: [True]

sabr_portfolio:
  class_name: Portfolio
  params:
    sde:
      ref: sabr_sde
    client_trade_poisson_rate: 1.0
    client_options:
      class_name: VanillaOption
      params:
        sde:
          ref: sabr_sde
        call: [True]
        moneyness: [1.0]
        ttm: [60]
        shares: [-1.0]
        sim_moneyness_mean: 1.0
        sim_moneyness_std: 0.0
        sim_ttms: [60]
        sim_call: [True]
    hedging_options:
      class_name: VanillaOption
      params:
        sde:
          ref: sabr_sde
        sim_moneyness_mean: 1.0
        sim_moneyness_std: 0.0
        sim_ttms: [30]
        sim_call: [True]

bsm_sde:
  class_name: BSMSimulator
  params:
    s: 10.0
    vol: 0.3

sabr_sde:
  class_name: SABRSimulator
  params:
    s: 10.0
    vol: 0.3
    volvol: 0.3