# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.1  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.1
# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.2  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.2
# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.3  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.3
# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.4  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.4
# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.5  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.5
# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.6  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.6
# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.7  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.7
# python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/robustness/sabr_vol0.8  --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.8

# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.1  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.1
# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.2  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.2
# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.3  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.3
# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.4  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.4
# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.5  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.5
# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.6  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.6
# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.7  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.7
# python run_benchmark.py @run_configs/agents/gamma.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/gamma/sabr_vol0.8  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.8

# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.1  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.1
# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.2  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.2
# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.3  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.3
# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.4  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.4
# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.5  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.5
# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.6  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.6
# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.7  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.7
# python run_benchmark.py @run_configs/agents/vega.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde/vega/sabr_vol0.8  --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.vol=0.8

for vol in {1..8}; do
    python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_mixsde_vanilla.yaml --logger_prefix=policies/bsm_vanilla/dr_mixsde_2/robustness/sabr_volvol0.$vol --eval_only --agent_path=policies/bsm_vanilla/dr_mixsde_2 --sabr_portfolio.client_trade_poisson_rate=1.0 --sabr_sde.volvol=0.$vol
done
